# docker-compose.yml
services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CHATBOT_API_KEY=${CHATBOT_API_KEY}
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge