name: Docker CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [Frontend, Backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      # BƯỚC MỚI: Định nghĩa biến service_name_lower
      - name: Set lowercase repository name
        id: repo_name
        run: echo "SERVICE_LOWERCASE=${{ lower(matrix.service) }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          # ĐÃ SỬA: Sử dụng output từ bước trên để có tên repository chữ thường
          tags: luat123/${{ steps.repo_name.outputs.SERVICE_LOWERCASE }}:latest
