name: Docker CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [Frontend, Backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # ĐÃ SỬA: Thêm './' vào context để chắc chắn đây là đường dẫn tương đối
          context: ./${{ matrix.service }}
          # ĐÃ SỬA: Thêm './' vào file path
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: luat123/${{ matrix.service }}:latest
