name: Docker CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [Frontend, Backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      # BƯỚC SỬA LỖI CUỐI CÙNG: Sử dụng lệnh shell 'tr' thay vì hàm 'lower()'
      - name: Export lowercase tag name (Shell Fallback)
        id: set_tag_name
        run: |
          # Dùng 'tr' để chuyển đổi giá trị matrix.service sang chữ thường
          TAG_NAME_LOWERCASE=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')

          # Xuất biến ra $GITHUB_OUTPUT để bước tiếp theo có thể sử dụng
          echo "TAG_NAME_LOWERCASE=$TAG_NAME_LOWERCASE" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          # SỬ DỤNG: Lấy output từ bước set_tag_name
          tags: luat123/${{ steps.set_tag_name.outputs.TAG_NAME_LOWERCASE }}:latest
